volumes:
  sqlite_db:
services:
    api:
      build: ./api
      volumes:
        - sqlite_db:/var/www/html/database
      ports:
        - 8000:80
    web:
      build: ./web
      ports:
        - 8080:80